CREATE DATABASE IF NOT EXISTS lab_mysql;

USE lab_mysql;

DROP TABLE IF EXISTS CAR;
CREATE TABLE CAR (
    VIN VARCHAR(17) PRIMARY KEY,
    manufacturer VARCHAR(50),
    model VARCHAR(50),
    year INT,
    color VARCHAR(20)
);

DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER (
    customerID INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    phone VARCHAR(15),
    email VARCHAR(100),
    address VARCHAR(255),
    city VARCHAR(100),
    state_province VARCHAR(100),
    country VARCHAR(100),
    zip_postal_code VARCHAR(20)
);

DROP TABLE IF EXISTS SALESPERSON;
CREATE TABLE SALESPERSON (
    staffID INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    store VARCHAR(100)
);

DROP TABLE IF EXISTS INVOICE;
CREATE TABLE INVOICE (
    invoiceNumber INT AUTO_INCREMENT PRIMARY KEY,
    date DATE,
    carVIN VARCHAR(17),
    customerID INT,
    staffID INT,
    FOREIGN KEY (carVIN) REFERENCES CAR(VIN),
    FOREIGN KEY (customerID) REFERENCES CUSTOMER(customerID),
    FOREIGN KEY (staffID) REFERENCES SALESPERSON(staffID)
);
